server {
    listen 80;

    client_max_body_size 20M;

    location /api/segment/ {
        proxy_pass http://segmentation-api:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 120s;
    }

    location /api/classify/ {
        proxy_pass http://classification-api:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 120s;
    }

    location / {
        default_type application/json;
        return 200 '{"system":"PBL6 Lung X-ray","status":"gateway running"}';
    }
}